### ISSUE TITLE
How to fine-tune PIE on customized dataset?

### ISSUE THREAD

**Issue by hqsiswiliam** [awasthiabhijeet/PIE#10]
Hi Authors,

Thanks for your great work! Now I am stuck at fine-tuning **pre-trained PIE** on **customized data**, is there any way to do so? Many thanks for your reply.

**Comment by awasthiabhijeet** [comment]
Hi,
Please read the instructions [here](https://github.com/awasthiabhijeet/PIE/blob/master/example_scripts) and checkout end_to_end.sh

Since you only need to fine-tune pre-trained PIE, In [preprocess.sh](https://github.com/awasthiabhijeet/PIE/blob/master/example_scripts/preprocess.sh) you can comment out part of the code which extracts common insertions. 

While using word_edit_model.py for training, you will need to pass the path of pre-trained PIE to initialize the PIE model.

**Comment by hqsiswiliam** [comment]
> Hi,
> Please read the instructions [here](https://github.com/awasthiabhijeet/PIE/blob/master/example_scripts) and checkout end_to_end.sh
> 
> Since you only need to fine-tune pre-trained PIE, In [preprocess.sh](https://github.com/awasthiabhijeet/PIE/blob/master/example_scripts/preprocess.sh) you can comment out part of the code which extracts common insertions.
> 
> While using word_edit_model.py for training, you will need to pass the path of pre-trained PIE to initialize the PIE model.

Thanks a lot, I will try it out.

**Comment by r-reilly** [comment]
Hi! does this mean to use `  --init_checkpoint=pie_model.ckpt` in pie_train.sh ?

**Comment by bexxxxx** [comment]
Hi @awasthiabhijeet @hqsiswiliam does this mean to change the `init-checkpoint` in pie_train.sh from bert to pie_model.ckpt ?
